# Generated by Django 6.0.7 on 2026-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('minimum_experience', models.FloatField()),
                ('education_required', models.CharField(max_length=100)),
            ],
        ),
    ]
