# Generated by Django 6.0.7 on 2026-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
