# Generated by Django 6.0.7 on 2026-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobrole_strengths_jobrole_summary_jobrole_weaknesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='minimum_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
