# Generated by Django 6.0.7 on 2026-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='communication_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='hiring_recommendation',
            field=models.CharField(blank=True, choices=[('Strong Hire', 'Strong Hire'), ('Hire', 'Hire'), ('Hold', 'Hold'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_recording',
            field=models.FileField(blank=True, null=True, upload_to='interview_recordings/'),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
