# Generated by Django 6.0.7 on 2026-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0002_interview_ai_feedback_interview_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interview',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
