# Generated by Django 6.0.7 on 2026-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_applied_job_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_resume',
            field=models.TextField(blank=True),
        ),
    ]
