# Generated by Django 6.0.7 on 2026-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_ai_recommendation_candidate_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_score',
            field=models.FloatField(default=0),
        ),
    ]
