# Generated by Django 6.0.7 on 2026-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_education_score_candidate_experience_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
